# Generated by Django 5.1.2 on 2024-10-23 14:37

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('conteudo', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
